Feat: Add all_burst_number
BlueBrain/eFEL pull request #367
Opened 2024-02-06 08:57 UTC by arnaudon

## Description

See docstring for details, WIP for work with @PolinaL 

I'll add test/doc/changelog once stable 

## Checklist:
- [ ] Unit tests are added to cover the changes (skip if not applicable).
- [ ] The changes are mentioned in the documentation (skip if not applicable).
- [ ] CHANGELOG file is updated (skip if not applicable).

2024-02-06 09:47 UTC, anilbey requested changes
Thanks @arnaudon  looks very good. I added a few remarks.

Could you also add a test to it?

In the test could you check when number of isis is <= 1?

Also, will it work when the number of isis is equal to 2?

2024-02-06 09:47 UTC, anilbey commented on efel/pyfeatures/pyfeatures.py
> +def all_burst_number():
Wouldn't it be more descriptive to call it something like  `count_burst_events_by_isi_clustering`?

2024-02-06 09:47 UTC, anilbey commented on efel/pyfeatures/pyfeatures.py
> +    from sklearn.cluster import KMeans
Could you put it at the top of the file and then add `scikit-learn>=X.Y.Z` to `setup.py`, where X.Y.Z is the version you tested?

2024-02-06 09:47 UTC, anilbey commented on efel/pyfeatures/pyfeatures.py
> +def all_burst_number(raise_warnings: bool = False) -> np.ndarray:
Wouldn't it be more descriptive to name it something like `count_burst_events_by_isi_clustering`?

2024-05-13 08:06 UTC, arnaudon commented
I'm closing this, we can use https://github.com/BlueBrain/eFEL/pull/391

2024-05-13 08:07 UTC, closed without merging